; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
upload_protocol = espota
upload_port = 192.168.0.18
platform = espressif32
board = esp32doit-devkit-v1
framework =  arduino ;, espidf
extra_scripts = pre:extra_script.py

lib_deps =
	arduino-libraries/NTPClient @ ^3.2.1
	arduino-libraries/Arduino_JSON @ ^0.2.0
	adafruit/Adafruit ADS1X15 @ ^2.4.0
	adafruit/DHT sensor library @ ^1.4.4
	adafruit/Adafruit Unified Sensor @ ^1.1.7
	adafruit/Adafruit BusIO @ ^1.14.1
	ihormelnyk/OpenTherm Library @ ^1.1.4
    esp32async/AsyncTCP@^3.4.9
	esp32async/ESPAsyncWebServer@^3.8.1
	ayushsharma82/WebSerial@^2.1.1
